// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zufyvjomyontfmzhbywm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1Znl2am9teW9udGZtemhieXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDIxNTksImV4cCI6MjA2NjQxODE1OX0.4nllOWf3HA-8ghD6UGAjLpbW-5K6Rum9uWbzuze56pU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);